### ISSUE TITLE
Why do I get RuntimeError: This event loop is already running?

### ISSUE THREAD

**Issue by dyus1983** [0liu/ibstract#1]
```
# Clear Stock table
engine.execute(meta.tables['Stock'].delete())

# A user coroutine to get wider range of historical data than those existing in MySQL.
# Data existing in MySQL will not be downloaded, but combined with downloaded data.
async def histdata_db(req, broker, loop):
    histdata = await ibstract.get_hist_data(req, broker, mysql={**db_info, 'loop': loop})
    return histdata

req = ibstract.HistDataReq('Stock', 'UPRO', '1d', '20d', ibstract.utils.dtest(2017, 9, 9))
broker = ibstract.IB('127.0.0.1', 4002)
loop = asyncio.get_event_loop()
```

Log output of this step:
2017-10-22 19:27:25,219 ib_insync.client INFO Connecting to 127.0.0.1:4002 with clientId 26...
2017-10-22 19:27:25,222 ib_insync.client INFO Connected
2017-10-22 19:27:25,227 ib_insync.client INFO Logged on to server version 118
2017-10-22 19:27:25,271 ib_insync.wrapper INFO Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2017-10-22 19:27:25,272 ib_insync.client INFO API connection ready
2017-10-22 19:27:25,323 ib_insync.ib INFO Synchronization complete
2017-10-22 19:27:25,324 ib_insync.ib INFO Disconnecting from 127.0.0.1:4002, 254 B sent in 8 messages, 20.1 kB received in 158 messages, session time 146 s.
2017-10-22 19:27:25,326 ib_insync.client INFO Disconnected

Then when I run:
 `hist = loop.run_until_complete(histdata_db(req, broker, loop))`

I get:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-77-f1bd8a207172> in <module>()
----> 1 hist = loop.run_until_complete(histdata_db(req, broker, loop))

~/anaconda3/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    452         future.add_done_callback(_run_until_complete_cb)
    453         try:
--> 454             self.run_forever()
    455         except:
    456             if new_task and future.done() and not future.cancelled():

~/anaconda3/lib/python3.6/asyncio/base_events.py in run_forever(self)
    406         self._check_closed()
    407         if self.is_running():
--> 408             raise RuntimeError('This event loop is already running')
    409         if events._get_running_loop() is not None:
    410             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by dyus1983** [comment]
This error is raised after I run:
`ib_insync.util.startLoop()`
Is there a way to use ib_insync.util.startLoop() together with ibstract?

**Comment by 0liu** [comment]
Looks `ib_insync.util.startLoop()` registers asyncio integration with ipykernel and keeps loop running at background, so notebooks can be live updated. Even if you run a simple coroutine with `loop.run_until_complete()` will give the same error since loop is already running, as error message states:

```python
import asyncio
import ib_insync
ib_insync.util.startLoop()
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.sleep(1))
```

So this is generally about how to drive a coroutine with async widget in notebook, nothing specific about ibstract. Can you please try `t = asyncio.ensure_future(histdata_db(req, broker, loop))` and get return by `t.result()`?

**Comment by dyus1983** [comment]
`t.result()` returned the historical data.
So, is this a suggested way to get the historical data?

**Comment by 0liu** [comment]
The way to drive ibstract coroutine depends on application context. So does for all libraries. As commented above, this is a general question about how to drive a coroutine, not specifically related to ibstract.
